### ISSUE TITLE
open source VLSI1000 firmware?

### ISSUE THREAD

**Issue by jeremyabel** [adafruit/Adafruit-Audio-FX-Sound-Board-PCBs#1]
If I'm asking for too much, that's totally cool but I figured it's worth a shot. Would y'all be able to open source the custom firmware for the VLSI1000?

**Comment by ladyada** [comment]
we cannot because its under VLSI's license. you can download it from their page but we cant redistribute :(

**Comment by jeremyabel** [comment]
ah ok, is it just the default firmware?

**Comment by ladyada** [comment]
pretty much!
