### ISSUE TITLE
EAGLE Files don't open in EAGLE...

### ISSUE THREAD

**Issue by AudioRich** [adafruit/Adafruit-Audio-FX-Sound-Board-PCBs#2]
The brd and sch files don't open in EAGLE 9.6 returns 'This is not an EAGLE file' please migrate the files to the latest version or at least tell me what I'm doing wrong so I can open them before deleting my comment...

**Comment by ladyada** [comment]
hi - the files open in eagle 9.6 for us - you need to download them proplerly
![image](https://user-images.githubusercontent.com/1214161/121576060-07818a80-c9f6-11eb-890d-12dac9cbff30.png)
